language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
branches:
  only:
  - master
  - stable
after_success:
  - export CODECOV_TOKEN="a2cb72ad-d773-4f47-ab17-398b2670489d"
  - npm i codecov
  - codecov
